theme = "coder" # set the theme

[params] # theme parameters
    author = "Jarrod Nelson" # author's name
    info = "Up and Coming Web Developer | Watch This Space!!" # author's job title or info
    description = "Jarrod Nelson's personal website" # site description
    keywords = "blog, developer, personal, portfolio" # site keywords
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/jnelson83/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/johndoe/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Portfolio"
    weight = 1
    url = "/portfolio/"